package wah

var isDebug bool = false
var isFirstDetect = true
type CCW int

const (
	MAP_STRUCTURE_ITER = iota + 1
	RANDOM_NUMBER_GENERATION
	GF_DECLARATION
	UNCHECKED_INPUT_ARGUMENTS
	UNHANDLED_ERROR
	USED_GOROUTINE
	PHANTOM_READS
	READ_YOUR_WRITE
	RANGE_QUERY_RISK
)

func (c CCW) String() string {
	return [...]string{"MAP_STRUCTURE_ITER", "RANDOM_NUMBER_GENERATION",
		"GF_DECLARATION", "UNCHECKED_INPUT_ARGUMENTS", "UNHANDLED_ERROR", "USED_GOROUTINE",
		"PHANTOM_READS", "READ_YOUR_WRITE", "RANGE_QUERY_RISK"}[c-1]
}
